
/*

select * from SLN_ADMISIONS where CLASS ='7' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='7',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('V.AKHILA GRACE','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','6305566294','F','','V.SURESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.BHUVIKA REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'DHAMARKUPPAM','8179771427','F','','P.DHANAMJEYULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K,DHARSHU','',@CLASS_NAME,@ACADEMIC_YEAR,'GUNDRAGINDLU','8978253269','F','','K.GOPI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('J.DHANU SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9440077774','F','','J.HARI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.HASINI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9441643065','F','','B.SWAMY RAJU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.REEDY HARSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9618006868','F','','C.BANGARAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.JYOSHNA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704763969','F','','P.MANI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.MADHUPRIYA','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINTHATHOPU','9652947981','F','','M.GOVINDHU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.MOULIKA','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PET','6281492300','F','','K.PUNDARIKA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DM.SADHANA SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7801071027','F','','D.MALLIKARJUN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.SAHASRA','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PET','9704112275','F','','VN.JYOTHIVARAPRASADH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.SAARIKA','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8500951380','F','','V.SANKAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.SONIYA','',@CLASS_NAME,@ACADEMIC_YEAR,'KMV.PALI','9912038330','F','','P.SIDDAREDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.THANUJA SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'M.KRISHNAPURAM','6364368120','F','','P.SWAMINADH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.VARSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9542005469','F','','C.SEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.YOGA','',@CLASS_NAME,@ACADEMIC_YEAR,'PALLIPATTU','8897832509','F','','S.SUDHARSAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.SUSMITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAGERIGADONA','9618271537','F','','C.VADIVELU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.PUJITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'PADAMASARASSU','8971008954','F','','G.VARUN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.AKSHA','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','9963635321','F','','B.GOPINADH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N.AKASH','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREDDY KANDRIGA','9740954341','M','','N.VENKATESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('R.AKHIL','',@CLASS_NAME,@ACADEMIC_YEAR,'EDIGAPALLI','8978772308','M','','R.BALAJI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.HEMANTHKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9441996787','M','','K.VENKATA REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.JOVAN SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9866036142','M','','K.DHAMU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.JASON','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','9100249097','M','','V.PALRAJ','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.JASWANTH','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','9704836451','M','','C.CHARLESS','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N.JESWANTH','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW','9704597727','M','','N.MOHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('KS.KISHORE RAJU','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','9444272826','M','','K.STEPHEN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('J.PUNITH','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7032177142','M','','J.MOHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.SANDEEPYADAV','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9885437428','M','','M.MUNIKUMAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A.YUGESH REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM .PURAM','8008470396','M','','A.RAMESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.NIKHIL','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMABAPURAM','9515189120','M','','G.HARIKRISHNA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A.NARENDRA YADAV','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8985324770','M','','A.MADHAVA ','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
