/*

select * from SLN_ADMISIONS where CLASS ='Jr Inter' and Section='CEC'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='Jr Inter',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='CEC'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section

insert into SLN_ADMISIONS values('P SRIVALLI','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTTARUVEDU','9515023734','F','','P ANKAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K MADHAVI','',@CLASS_NAME,@ACADEMIC_YEAR,'AMMAVARIGUNTA','9392130528','F','','K JANAKI RAMIREDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S NIKITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'R K M PURAM','6301715925','F','','S VENKATACHALAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G GOWRI PRIYA','',@CLASS_NAME,@ACADEMIC_YEAR,'PATHAGUNTA','9032261218','F','','G SADHASIVA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P CHARAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','8096076766','M','','P SOMASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V GURU CHARAN','',@CLASS_NAME,@ACADEMIC_YEAR,'MITTAKANDRIGA','9573063956','M','','V SUBRAMANYAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('R SARAVANA','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','8106024711','M','','R MOHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P ADIKESHAVULU','',@CLASS_NAME,@ACADEMIC_YEAR,'G M PURAM','8977179723','M','','P MADHU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N JASWANTH','',@CLASS_NAME,@ACADEMIC_YEAR,'K M PURAM','9063164650','M','','N ESWARAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P JAGAN','',@CLASS_NAME,@ACADEMIC_YEAR,'MUDDIKUPPAM','9391085187','M','','P DHAMODHARAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P RAGHAVA','',@CLASS_NAME,@ACADEMIC_YEAR,'K M PURAM','8790754861','M','','P RAMESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M MANOJ','',@CLASS_NAME,@ACADEMIC_YEAR,'MITTAKANDRIGA','8179636899','M','','M DEVADAS','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
