/*

select * from SLN_ADMISIONS where CLASS ='UKG' and Section='B'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='UKG',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='B'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section



insert into SLN_ADMISIONS values('Chareshma A','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9603415816','F','','A DHANASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Gayani N','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9652022413','F','','N.KIRAN KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Harshitha D','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','8247040353','F','','T DHANAPAL','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Likithapriya K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9182004640','F','','K NAGAMUNEDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mithusri G','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9550075775','F','','M.GIRI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Nithyasree G','',@CLASS_NAME,@ACADEMIC_YEAR,'PADMASARASU','8008440905','F','','G.MOHAN BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Reshmitha reddy','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','7993665590','F','','P MURALI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Shaanvi sree C','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','7993488221','F','','C.RAJASEKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yakshitha N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9676827524','F','','N.MAHESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Keerthana.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9121668302','F','','K.BALA MURALI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhamiya','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR(PHW)','9885226020','F','','K.BHASKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bharath patel P','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8884902540','M','','R.CHETHAN PATEL','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhavan Yadhav','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9985035173','M','','J.PRASADH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Darshith K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8520904395','M','','K.THYAGU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhakshay R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9550522658','M','','R RAJESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhanush','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9652268393','M','','K.KUPPAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dishwanth Yadav.P','',@CLASS_NAME,@ACADEMIC_YEAR,'KANAKAMAKANDRIGA','9441523182','M','','P CHANDRA BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Gurucharan R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9502338794','M','','R.SRIKANTH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Harish kalyan N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9542817108','M','','N.GOVINDAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hethvik Krishna','',@CLASS_NAME,@ACADEMIC_YEAR,'C.D.KANDRIGA','8660513377','M','','P.RAVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jashwanth S','',@CLASS_NAME,@ACADEMIC_YEAR,'INDIRA COLONY','9959026328','M','','S.CHAKRAVATHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Medvin G','',@CLASS_NAME,@ACADEMIC_YEAR,'MAMDEDU(HW)','9032117022','M','','G.E.SWARAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Saicharan T','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9849140990','M','','T SURESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sanketh.R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9666056541','M','','R.DHARMA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Santhosh.N','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTHACHERUVU','9177982818','M','','N.SAI KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sathwik reddyK','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9908736560','M','','K.RAJENDRA REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Shyamthrivedh K','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','7095658584','M','','K.SAI KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sohithkumar C','',@CLASS_NAME,@ACADEMIC_YEAR,'CHITHAMANDI','9492629076','M','','C.CHIRANJEEVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yashvanth sai','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9347128275','M','','M.ROHINI KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
