
/*

select * from SLN_ADMISIONS where CLASS ='2' and Section='B'
order by 1
*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='2',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='B'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section

insert into SLN_ADMISIONS values('Chathurya.N','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8500096434','F','','N CHANDRASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Deekshitha.V','',@CLASS_NAME,@ACADEMIC_YEAR,'INDHIRA COLONY','8790945871','F','','V DEVENDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('GEETHIKA.R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9618403247','F','','R RAJESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Iniya.C','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','8978744254','F','','C.Dinesh Kumar','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kruthika.K','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','8374733534','F','','K DINAKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kusuma.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KALLIKIRINDLU','9347859390','F','','K RAJENDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Manaswini.A','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9502470788','F','','A JAYACHANDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MIDULA.K','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINTHAMANDI','7330880208','F','','K SANKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Neethasree.B','',@CLASS_NAME,@ACADEMIC_YEAR,'GERIGIDHONA','9177606057','F','','B GAJENDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M Rahena','',@CLASS_NAME,@ACADEMIC_YEAR,'PALLIPATTU','883893716','F','','M BASHA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHAZIP.P','',@CLASS_NAME,@ACADEMIC_YEAR,'','0','F','','','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sumasree.M','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','7729077841','F','','M DHAMODHAR REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thaanya Reddy ','',@CLASS_NAME,@ACADEMIC_YEAR,'G.T.KANDRIGA','9502131077','F','','P MURALI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Vinusha.J','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9849140990','F','','J PRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chathwick Sai AP','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9705651106','M','','A.P.UDAY KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chethan.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8500815800','M','','K.VEMAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Darshith sai .V','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','7799112489','M','','V VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.Dharniswar','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','9949579294','M','','B BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dusyanth','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','8897121071','M','','K RAJINI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Karthikeya.R','',@CLASS_NAME,@ACADEMIC_YEAR,'EDIGA PALLI','9550316343','M','','R BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Lirish kumar.M','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','8184951451','M','','M BHARTH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Paarijith Kumar','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9154424670','M','','S LOKESHWAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Vian.P','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','7416639915','M','','P PRAVEEN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yathwin.c','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','7993488221','M','','C RAJASHEKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
