
/*

select * from SLN_ADMISIONS where CLASS ='4' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='4',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('Bruthvardhini.G','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9000976302','F','','G.DEVARAJULU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chitraja.K','',@CLASS_NAME,@ACADEMIC_YEAR,'C.D.KANDRIGA','9177307485','F','','K.SOMANADHAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhara J','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8886459167','F','','J.CHIRANJEEVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hershitha.P','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','7893734905','F','','P.KISHORE','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Janani.K','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIKAPALAM ','9949581737','F','','K.ESWARANAND','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thanusree.B','',@CLASS_NAME,@ACADEMIC_YEAR,'KESAVAKUPAM','7093421470','F','','B.GOPI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thrijal.C','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','6301315940','F','','C.GANGADHARAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Likitha.M','',@CLASS_NAME,@ACADEMIC_YEAR,'KESAVAKUPAM','8008817531','F','','M.VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mokshitha.K','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9701936277','F','','K.KUMARA RAJU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Radha J','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8886459167','F','','J CHIRANJEEVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Rupa.G','',@CLASS_NAME,@ACADEMIC_YEAR,'SIVALAYAMSTREET(KNR)','9581070860','F','','G.BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Ritika K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9959687068','F','','K.SHYAM LAL','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhargav.M','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9502885009','M','','M.VIJAYA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bobbyvibushan.k','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9704181566','M','','K.BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hemanth Kumar.S','',@CLASS_NAME,@ACADEMIC_YEAR,'KANAKAMAKANDRIGA','7671822737','M','','S.RAMESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hishanth.P','',@CLASS_NAME,@ACADEMIC_YEAR,'BHARATHIPUTAM','9989797838','M','','P.BALA KRISHNA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jeevan Joshith.A','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9550303457','M','','A.BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jyothi Krishna.M','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPAM','8008165415','M','','M.VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Praneeth.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8520904395','M','','K.THYAGU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thoufik.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','6309382047','M','','K.MAHAMMAD SIDDIK','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
