
/*

select * from SLN_ADMISIONS where CLASS ='9' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='9',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section



insert into SLN_ADMISIONS values('J.DHAKSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8142760635','F','','J.RAJASEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VS.DHARSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9052240426','F','','VK.SRINIVASULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.DISOWMYA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9866036142','F','','K.DHAMODHARAM','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('J.GNANAJYOTHI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7032177142','F','','J.MOHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.GOWTHAMI','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRENDLU','9502885122','F','','M.VIJAYKUMAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.POOJA','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9490505235','F','','K.GANESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.SOFIYA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9642099696','F','','D.K.KHADHAR BASHA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.VAASTHLYA','',@CLASS_NAME,@ACADEMIC_YEAR,'VENUGOPALAPURAM','9959670687','M','','S.BALAKRISHNA REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('KS.ABHISJEK','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','9444272826','M','','K.STEPHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.AJAY','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRENDLU','9573071550','M','','K.ESWAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.CHARANTEJ','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9676600636','M','','M.RAJESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.DONI','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAGARIGADONA','9951921782','M','','B.VENUGOPAL','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.GIRIDHAR','',@CLASS_NAME,@ACADEMIC_YEAR,'SANAKUPPAM','9121997592','M','','K.CHANDRASEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.GOPICHANDH','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8142078501','M','','T.RAVI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DM.GOWTHAM SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9963554686','M','','D.MALLIKARJUN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.JACOB','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','9100249097','M','','V.PALRAJ','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.LAYAVARDHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9493372897','M','','K.SRIDHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Y.LOKESH','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAGARIGADONA','8978372961','M','','Y.NARASIMHULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.MADHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'PALLIPATTU','7338790092','M','','V.BHASKAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.MOHAMAD FARHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9573801397','M','','S.JAILABDEEN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.NAVEEN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704026276','M','','T.ASHOK','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.NIRANJAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9652274168','M','','J.VELU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.PUNITHKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'KMV.PALLI','9912038330','M','','P.SIDDAREDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.RAKESH','',@CLASS_NAME,@ACADEMIC_YEAR,'GUNDRAJA INDLU','8374522215','M','','K.GOPI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.RISHI','',@CLASS_NAME,@ACADEMIC_YEAR,'PALLIPATTU','8897832509','M','','S.SUDHARSHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.SAI SUDHEER','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7036273555','M','','K.HARISH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.THOSHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704763969','M','','P.MANI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.TIPPUCHARAN','',@CLASS_NAME,@ACADEMIC_YEAR,'T.KOTHUR','7893221383','M','','K.NAGARAJ REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.DHANUSH','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTHAPALLI MITTA','9701316464','M','','P.GUNA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.VARUNTEJ','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9542005469','M','','C.SEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C.YAGNESH BABU','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9618644685','M','','C.BABU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
