
/*

select * from SLN_ADMISIONS where CLASS ='10' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='10',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('D.AFRIN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9701861466','F','','D.MABUBASHA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.AKHILA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8971008954','F','','G.VARUN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.BHAVITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKADRIGA','9000976302','F','','G.DEVARAJULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.BHAVYA SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKADRIGA','9985146016','F','','G.PADAMANABHAM','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.BINDHU SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9949779098','F','','K.THYAGARAJULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.HEMAVATHI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8179065606','F','','T.AHOK','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.JAYASHALINI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9573588422','F','','P.NITHYA PUJAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.MANASA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9573588422','F','','S.NARASIMHULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.NAGESWARI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7799486548','F','','K.NAGARAJU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.NANADINI','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PETA','7702941355','F','','V.MUNASWAMY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.RAMYA','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHAGUNTA','9491771841','F','','K.MOHANBABU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.THASEEN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9642099696','F','','D.KADHARBASHA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.PRAVEENA','',@CLASS_NAME,@ACADEMIC_YEAR,'SUDDHAGUNTA','9398802700','F','','V.SUDHAKAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.BOBBY','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8985325118','M','','K.MADHU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N.CHAITHANYA','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREDDYKANDRIGA','9740954341','M','','N.VENKATESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.CHAKRADEV','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIKAPALEM','9949581737','M','','K.ESWARANAND','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.CHARANTEJ','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704022728','M','','T.RAVI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.GAGAN SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9652267201','M','','M.RAMESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.GOWTHAM ROYAL','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','9441776170','M','','M.MURALI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.HARSHA','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9550302761','M','','T.GANGADHARAM','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.HARSHAVARDHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAMUDIKUPPAM','6379159383','M','','G.SRINIVASULA REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('J.JASWANTHKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8142760635','M','','J.RAJASEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.MOTHISHA SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8978114976','M','','R.DASS','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.NIRANJAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9676131010','M','','P.DAIVASIKHAMANI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.PREMKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'AYYANGARIPALLI','9177689598','M','','P.RAMAGOVINDH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.RAHUL','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9440860562','M','','K.NETHAJI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.ROHITH REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PETA','9441601127','M','','S.NAGARAJU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('E.SUDHARSHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PETA','9618378961','M','','E.LAKSHMAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('E.SURYA PRAKASH','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB.PETA','9618378961','M','','E.LAKSHMAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B.HARSHAVARDHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9703374930','M','','B.JAGADEESWARAO','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.BHARATH','',@CLASS_NAME,@ACADEMIC_YEAR,'CHAVATGUNTA','8885456957','M','','T.RAVI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.MAHITH REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'BHARATHIPURAM','9676316118','M','','M.KODANDA REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
