
/*

select * from SLN_ADMISIONS where CLASS ='6' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='6',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('P. CHAITHRA YADAV','',@CLASS_NAME,@ACADEMIC_YEAR,'KANAKAMMA KANDRIGA','9441523182','F','','P CHANDRA BABU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N. HARINI','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9542817108','F','','N GOVINDAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N. HASINI','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTA CHERUVU, KNR','9494086719','F','','N RUDRAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D. HEMASRI','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNANAGAR STREET, KNR','8978114976','F','','R DOSS','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S. JAHNAVI','',@CLASS_NAME,@ACADEMIC_YEAR,'KANAKAMMA KANDRIGA','7671822737','F','','S RAMESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('KRITHIKA PATEL','',@CLASS_NAME,@ACADEMIC_YEAR,'BAZZAR STREET, KNR','9440809780','F','','SASIKANTH PATEL','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K POORNIMA','',@CLASS_NAME,@ACADEMIC_YEAR,'SURYAPALYAM','9573864911','F','','K MUNIRATHNAM REDDY','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S PUSHPITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'VENUGOPALAPURAM','9959670687','F','','S BALAKRISHNA','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N RAKSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREDDY KANDRIGA','7993499961','F','','N SEKHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S P SANATASNEEM','',@CLASS_NAME,@ACADEMIC_YEAR,'MUSLIM COLONY, KNR','9573801397','F','','S P JAILABDEEN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.TEJA SREE','',@CLASS_NAME,@ACADEMIC_YEAR,'C.D.KANDRIGA','7801010340','F','','P.SUBRAMANYAM','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.YASASWINI','',@CLASS_NAME,@ACADEMIC_YEAR,'VARALAKSHMI STREET ,KNR','9989034726','F','','K.NARENDRA BABU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.S.ABDUL MANNAN','',@CLASS_NAME,@ACADEMIC_YEAR,'OLD BUS STAND,KNR','8179635928','M','','G.LATHEEF','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.CHAKRADHAR','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNANAGAR STREET, KNR','9573188308','M','','M.RAJESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('R.BHUVANESWAR','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9618377754','M','','R.RAGHU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S.CHATHVIK','',@CLASS_NAME,@ACADEMIC_YEAR,'INDIRACOLONY','8179898014','M','','S.RAMU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.DIVYA CHARAN','',@CLASS_NAME,@ACADEMIC_YEAR,'RAGIMANU STREET ,KNR','9502798349','M','','K.MOHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.DIVYESH','',@CLASS_NAME,@ACADEMIC_YEAR,'APPACHARI STREET ,KNR','9493372897','M','','K.SRIDHAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.GURUDEEP YADAV','',@CLASS_NAME,@ACADEMIC_YEAR,'KUMMARAGUNTA STREET,KNR','9885437428','M','','M.MUNIKUMAR','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VS.HEMASAI','',@CLASS_NAME,@ACADEMIC_YEAR,'SIVALAYAM STREET ,KNR','9052676631','M','','VK.SRINIVAS','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.KIRAN KUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','8790618893','M','','G.DHNARAJ','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V.MOKSHITH SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNANAGAR STREET, KNR','7799112489','M','','V.VENKATESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M.NITHEESH','',@CLASS_NAME,@ACADEMIC_YEAR,'EDDARAPUKANDRIGA','800887531','M','','M.VENKATESH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D.REEHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR POLICE STATION,KNR','9347452782','M','','D.NOORUDDIN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.SHYAMKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','8985751245','M','','G.BALAJI','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('G.SRISANTH','',@CLASS_NAME,@ACADEMIC_YEAR,'APPACHARI STREET ,KNR','7337233952','M','','G.RAJENDRAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.TEJA','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','9553276502','M','','P.RAMULU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N.KARTHIKA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9591505519','M','','N.THIRUMALARAJU','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.YOGESH','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','8522916152','M','','P.MADHAN','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A.YOGAMRUTHA','',@CLASS_NAME,@ACADEMIC_YEAR,'PONNAGALLU','6383623582','M','','A.BHAKTHAVACHALAM','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('J.MURALIDHAR','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','7993067834','M','','J.GURAVAIAH','',@SECTION,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
