/*

select * from SLN_ADMISIONS where CLASS ='Jr Inter' and Section='BiPC'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='Jr Inter',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='BiPC'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section

insert into SLN_ADMISIONS values('M VANITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'RACHAPALYAM','9652917106','F','','M AMARNADH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M JANAVI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704366484','F','','M VASU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M VARSHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'GURAVARAJUGUNTA','7993791657','F','','M LOKANADHAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M EPSHIBHA','',@CLASS_NAME,@ACADEMIC_YEAR,'DHARMACHERUVU','7780143432','F','','M VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A PAVITHRA','',@CLASS_NAME,@ACADEMIC_YEAR,'ANNUR','8897077420','F','','A PRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C REKHA PRIYA DHARSHINI','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','7993172533','F','','C MOHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V CHAITHANYA','',@CLASS_NAME,@ACADEMIC_YEAR,'R K V B PETA','9502255232','F','','V GOVARDHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N JOSHNA','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','8790328901','F','','N CHARLES','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B PREETHI','',@CLASS_NAME,@ACADEMIC_YEAR,'MUDDIKUPPAM','7032914019','F','','B GANDHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K DIVYA KUMARI','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','8489762271','F','','K DINAKARAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K SWETHA','',@CLASS_NAME,@ACADEMIC_YEAR,'T K M PETA','8897436770','F','','K RAVIKUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K POOJASRI','',@CLASS_NAME,@ACADEMIC_YEAR,'KODHANDARAMAPURAM','7671898052','F','','K MUNIVELU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P POORNIMA','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTARUVEDU','8008164904','F','','P VELAYUDHAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A POOJADARSHINI','',@CLASS_NAME,@ACADEMIC_YEAR,'ANNURU','8008153906','F','','A BUJJIBABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P CHARAN TEJA','',@CLASS_NAME,@ACADEMIC_YEAR,'AARUMAKULAPALLI','9701316464','M','','P GUNASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A PURSHOTHAM','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9177243233','M','','A MANIKANTA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)

