/*

select * from SLN_ADMISIONS where CLASS ='Jr Inter' and Section='MPC'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='Jr Inter',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='MPC'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('P PALLAVI','',@CLASS_NAME,@ACADEMIC_YEAR,'CHAVATAGUNTA','9492854995','F','','P PARAMESHWAR REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P GAYATHRI','',@CLASS_NAME,@ACADEMIC_YEAR,'KMV PALLI','9542832744','F','','P VEMANA REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A SRAVANI','',@CLASS_NAME,@ACADEMIC_YEAR,'GUNDUPALLI','9347886741','F','','A CHANGALRAYULU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C POOJITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'PONNAGALLU','9963632663','F','','C GIRIBABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T KOWSALYA','',@CLASS_NAME,@ACADEMIC_YEAR,'R K V B PETA','6309376705','F','','T GOVARDHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P DILLISHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9642572654','F','','P RAJAGOPAL','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B PALLAVI','',@CLASS_NAME,@ACADEMIC_YEAR,'GOLLAPALLI','9100794013','F','','B VENKATARATNAM  ','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K POOJITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9642424505','F','','K DESAMMA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K HASINI','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9573071550','F','','K ESWARREDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P LOKESWARI','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9441573807','F','','P JAYARAMA REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M NEERAJA','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9502885009','F','','M VIJAY KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K CHANDU','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440274213','F','','K BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('V RAJINI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9885900626','F','','S VINAYAGAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T DHARANI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7674901811','F','','T RAMESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T LAAHARI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9391861275','F','','T VINAYAKA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K INDU','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440349913','F','','K BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T LAHARI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7674812521','F','','T PRAKASH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B SANDHYA','',@CLASS_NAME,@ACADEMIC_YEAR,'KURIVIKUPPAM','7780513886','F','','B SUBRAMANYAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B HEMALATHA','',@CLASS_NAME,@ACADEMIC_YEAR,'PERUMALLA PALLI','9912481456','F','','B JAYARAMA REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P BHAVITHA SRI','',@CLASS_NAME,@ACADEMIC_YEAR,'T K M PETA','7013795835','F','','P VIJAY KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M KAVYA KEERTHANA','',@CLASS_NAME,@ACADEMIC_YEAR,'ANNUR','9912154775','F','','M VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K BATHEMMA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7842146027','F','','K DHARMAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('B JAGADEESHWAR REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'GAZANKI PALLALU','6303582832','M','','B GURUSWAMI REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M VENKATESH','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9959412452','M','','M GANAPATHI REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S DHANUSH','',@CLASS_NAME,@ACADEMIC_YEAR,'SUDDAGUNTA','9581601093','M','','S LOKANADHAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C HARI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9493816008','M','','C CHANDRA SEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N CHANUKYA PRASAD','',@CLASS_NAME,@ACADEMIC_YEAR,'PERUMALLA PALLI','9989928190','M','','N VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N DALAR SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KM PURAM','8008156215','M','','N DAMODHAR REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C MAHESH REDDY','',@CLASS_NAME,@ACADEMIC_YEAR,'GODUGUCHINTHA','9390203497','M','','C CHANDRAMOHAN REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K HARSHA VARDHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9491771841','M','','K MOHAN BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C THULASIRAM','',@CLASS_NAME,@ACADEMIC_YEAR,'INDIRA COLONY','8790284286','M','','C NAGARAJ','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A DILEEP','',@CLASS_NAME,@ACADEMIC_YEAR,'SADDIKULLUPALLI','9963019472','M','','A SEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P DHANUSH','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8522051941','M','','P MUNI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K BALAJI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9502573056','M','','K SURESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A SAI SANTHOSH','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','8008041130','M','','A SAHADEVULU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M RAHUL','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','7995778877','M','','M RAJESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P MADHU','',@CLASS_NAME,@ACADEMIC_YEAR,'MM KANDRIGA','9177037416','M','','P UMAPATHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('D SAI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9392315826','M','','D ASHOK','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('M HEMADRI','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7989282798','M','','M RAMESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('N TEJA','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9704597727','M','','N MOHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K DHAVEEDHU','',@CLASS_NAME,@ACADEMIC_YEAR,'BALIJAPALLI','9963003181','M','','K NAVEEN BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K MOHAN','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','8179757440','M','','K KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('A BHARATH','',@CLASS_NAME,@ACADEMIC_YEAR,'ROUTHUVANI GUNTA','9704025700','M','','A GUNTI REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P CHARAN TEJA','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIKAPALLAM','9676283494','M','','P VIJAY KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P BARGAV','',@CLASS_NAME,@ACADEMIC_YEAR,'EGUVA GARIGADONA','8790234607','M','','P MAHENDHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K VENKATESH','',@CLASS_NAME,@ACADEMIC_YEAR,'KANAKAMMA KANDRIGA','9100697049','M','','K GOPI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P MANIKANTA','',@CLASS_NAME,@ACADEMIC_YEAR,'KOTHURU','9573459288','M','','P GUNASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('E BHUVANESWAR','',@CLASS_NAME,@ACADEMIC_YEAR,'KATHIRAPALLI','9963352876','M','','E VASU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('S JANAKIRAM','',@CLASS_NAME,@ACADEMIC_YEAR,'KRISHNASAMUDHRAM','7893223141','M','','S HARIBABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('C MADHAN KUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'NAKKALAMPALLI','9160602822','M','','C CHIRANJEEVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K DINAKAR','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','8374550521','M','','K VENKATESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P SIVAKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'POTHAVARIGUNTA','7075665364','M','','P VASU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T UTHEJKUMAR','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIKAPALLAM','7386468191','M','','T PRABHAKAR REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)


