
/*

select * from SLN_ADMISIONS where CLASS ='4' and Section='B'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='4',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='B'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('Deekshitha.p','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','8008897949','F','','P.JANARDHAN REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kundana.J','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8179031884','F','','J.KRISHNA PRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kumkum.Bhati','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9703000383','F','','Bhati SURESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mahalakshmi.T','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9490935202','F','','T.RRABHAKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sravya.K','',@CLASS_NAME,@ACADEMIC_YEAR,'SURAYYAPALLEM','9573864911','F','','K.MUNIRATHNAM REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thanusha.P','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDLU','9666209069','F','','P JAGADEESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thoshini.N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9542817108','F','','N GOVINDAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Viviyana.A.L','',@CLASS_NAME,@ACADEMIC_YEAR,'BAJANAGUDI KNR','9550204864','F','','A.L. LOKESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhavadeesh.B','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440010498','M','','B.ARUNACHALAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chaithnya Kumar.P','',@CLASS_NAME,@ACADEMIC_YEAR,'PADMASARASU','9703799552','M','','P.RAJENDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhathwik.G','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9985146016','M','','G.PADMANABAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dhanasekhar.G','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','9676332604','M','','G.RAJASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jaswanth.K','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','8374733534','M','','K.DINAKARPRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jithendra Kumar.M','',@CLASS_NAME,@ACADEMIC_YEAR,'BALASALAGUNTA','9553905941','M','','M.DHAMODHARAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Nicolas Franklin.S.R','',@CLASS_NAME,@ACADEMIC_YEAR,'KATHERAPALLI','9703923683','M','','S.RAVINDRAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Prudhweswar.K','',@CLASS_NAME,@ACADEMIC_YEAR,'BAJANAGUDI KNR','9494745480','M','','K.GOPI KRISHNA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Tendulkar Reddy.N','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9160556679','M','','N.KISHORE KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yashith Charan.D','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9550303038','M','','T.DINAKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DELWIN RAJ R.V','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9550456570','M','','M .RAJASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
