
/*

select * from SLN_ADMISIONS where CLASS ='3' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='3',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('Ananya.T','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8074696154','F','','T PRABHAKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhavishya.B','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440010498','F','','B ARUNACHALAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhavya sree.C','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9618006363','F','','C. BANGARAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chethna.J','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','8985932749','F','','J MADHU BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Deepu.k','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9182529141','F','','K KUSALA PRIYAVARADHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hethwika.P','',@CLASS_NAME,@ACADEMIC_YEAR,'P C.D.KANDRIGA','8790978737','F','','P RAVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Joshitha.C','',@CLASS_NAME,@ACADEMIC_YEAR,'EDIGAPALLI','8978022373','F','','C MUNI KRISHNAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kavya.K','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440349913','F','','K BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('LAHARI.B','',@CLASS_NAME,@ACADEMIC_YEAR,'MANBEDU','9346029757','F','','B CHANDRA BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mahalakshmi.B','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLLAGUNTA','9949579294','F','','P BABU RAO','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mokshitha.G','',@CLASS_NAME,@ACADEMIC_YEAR,'SIVALAYAM(ST)KNR','9581070860','F','','G BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Udanya.E','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9563515512','F','','E. RAMESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('AKHIL SAI .B','',@CLASS_NAME,@ACADEMIC_YEAR,'EGAVA GERIGIDHONA','9154423946','M','','B.YURVIKUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Chiradeep.V','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNANAGAR(ST)KNR','7032000806','M','','V AMARNTH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Harshad.K.S','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9885924358','M','','K.S JILANI BASHA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hemanth.N','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR ITI KNR','8464089408','M','','N.VARAPRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Heshwanth.B','',@CLASS_NAME,@ACADEMIC_YEAR,'INDIRA COLONY','9550973310','M','','B.MAHENDRAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Hitesh.M','',@CLASS_NAME,@ACADEMIC_YEAR,'SUDDAGUNTA','8179032184','M','','M SRINIVASULU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Jaikrishna.T','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','7287033073','M','','T.GANESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Koushik sai .C','',@CLASS_NAME,@ACADEMIC_YEAR,'EDIGAPALLI','9701140801','M','','C. SIVA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Mounish.T','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','8184809667','M','','T.UMASHANKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Municharvik Mourya .M','',@CLASS_NAME,@ACADEMIC_YEAR,'MANDAPAM(KNR)','9177370054','M','','M.MUNEESWARAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Naga chaitanya .P','',@CLASS_NAME,@ACADEMIC_YEAR,'BRAHIN (ST)KNR','9008884617','M','','P BASKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Nani .T','',@CLASS_NAME,@ACADEMIC_YEAR,'SADDIKULAPALLI','7993961079','M','','T VASU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('NAVADEEP.K','',@CLASS_NAME,@ACADEMIC_YEAR,'GURAVARAJAGUNTA','','M','','K MADHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PARTHIV RAJU.N','',@CLASS_NAME,@ACADEMIC_YEAR,'POLICE (ST) KNR','9441403293','M','','N.HITHENDRA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Pushwanth.S','',@CLASS_NAME,@ACADEMIC_YEAR,'PADMASARASU','9491292817','M','','M SURESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('ReedawnVarma.S','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9703081216','M','','E YUGANDHARVARMA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Rukesh.K','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','9440349913','M','','K BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sandeep Patel','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9440809780','M','','P SASHIKANTH PATAL','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Tharun Kumar.R','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9573241985','M','','R VENKATARAMANA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thulasi Ram.P','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9550569344','M','','P LAKSHMI PATHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Vedesh.S','',@CLASS_NAME,@ACADEMIC_YEAR,'SIVALAYAM(ST)KNR','9177891916','M','','S SRIKRISHNA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YASASWINI.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9502798394','M','','K MOHAN ACHARI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YASHITHA.K','',@CLASS_NAME,@ACADEMIC_YEAR,'GUNDARAJUINDLU','7330880208','M','','K SHANKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('CHARLES.T','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','9949222290','M','','T KIRAN BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('JASWANTH.M','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','7416340996','M','','PRETHAP','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
