
/*
truncate table SLN_ADMISIONS
select * from SLN_ADMISIONS where CLASS ='1' and Section='A'
*/
declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='1',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham'


delete from SLN_ADMISIONS where CLASS ='1' and Section='A'

insert into SLN_ADMISIONS values('KRISSANYA.K','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9908685970','F','','P NAVEEN KUMAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('LIYA .C','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','6301315940','F','','C.GANGADHARAM','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MUSKAN.S','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9150818470','F','','HUMAYUN.S','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('NEETHA SREE.T','',@CLASS_NAME,@ACADEMIC_YEAR,'phw knr','7893646765','F','','T GANESH','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('RITHWIKA .K','',@CLASS_NAME,@ACADEMIC_YEAR,'Indira Colony','8185014642','F','','K Giribabu','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHAANVI.P','',@CLASS_NAME,@ACADEMIC_YEAR,'TKMPETA','9553544388','F','','P.SIVAPRASADH','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHANVITHA .K','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9493314784','F','','K.NAGARAJU','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHAZIA ILMI .S','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','7995241221','F','','S.SHAJIDBASHA','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('TEJATHANYA SRI.P','',@CLASS_NAME,@ACADEMIC_YEAR,'ANURU','9347893607','F','','P.PRAVEEN KUMAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VEDHYA SREE.D','',@CLASS_NAME,@ACADEMIC_YEAR,'BANDREVUCOLONY','9701099157','F','','D.KOTI','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VARSHITHA .G','',@CLASS_NAME,@ACADEMIC_YEAR,'EAST STREET KNR','9154566930','F','','G RAJASEKHAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YESHITHA .C','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREDDY KANDRIGA','9000896630','F','','C.DURVASULU','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('ASWAIN RAJ.M','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9550456570','F','','M .RAJASEKHAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('CHETHAN.P','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','8008897949','M','','P.JANARDHAN REDDY','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DEVANSH.B','',@CLASS_NAME,@ACADEMIC_YEAR,'BANDREVUCOLONY','8374733470','M','','B BHASKAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DHAVAN .R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJYULAKANDIGA(HW)','9618149701','M','','R KIRAN ','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HIMACHARAN .B ','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAGERIGADONA','9848364909','M','','B.EASWRTEJA','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MAHESH BABU .P','',@CLASS_NAME,@ACADEMIC_YEAR,'GURAVARAJUGUNTA','8466803163','M','','P MUNEEDRA','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('POSHITH .C','',@CLASS_NAME,@ACADEMIC_YEAR,'PADHURUKUPAM','9542881145','M','','C SRIDHASR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PRATHAP .V','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9502424611','M','','V.SAMBA SIVA','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SANTHAN .R','',@CLASS_NAME,@ACADEMIC_YEAR,'PONNAGAL','7993290745','M','','R DORABABU','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHAREESH .P','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9949459776','M','','P.MURALI','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sohith P','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','6281619733','M','','P.Rajini','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SRIJAYA SANKAR.M','',@CLASS_NAME,@ACADEMIC_YEAR,'BALASALAGUNTA','9949654177','M','','M.DHAMODHARAM','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VICTOR .C.V ','',@CLASS_NAME,@ACADEMIC_YEAR,'PADIRIKUPPAM','9959197055','M','','C.VENKATESH','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YOGESH .K','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9989797838','M','','K.DEVENDRAN','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YUVANSH .C','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREEDY KANDRIGA','9552383026','M','','C.DILLIBABU','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('RICIKA SRI.C','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW (KNR)','9550177446','F','','C. UDYA KUMAR','','A','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
