

/*

select * from SLN_ADMISIONS where CLASS ='UKG' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='UKG',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section



insert into SLN_ADMISIONS values('Gurupriya V','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNAGARSTREET','9492380116','F','','V.AMMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Ilavarasi Isha K','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9626372145','F','','K.KISHOR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Joshna G','',@CLASS_NAME,@ACADEMIC_YEAR,'PADMASARASU','7729921038','F','','VENKAEY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Lakshmi G','',@CLASS_NAME,@ACADEMIC_YEAR,'VENUGOPALAPURAM','9618779811','F','','G.RAJENDRA REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Manasa K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9679530958','F','','K.PANDURANGA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Nandhana J','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9100775338','F','','MURAGA.J','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PRAVALIKA.P','',@CLASS_NAME,@ACADEMIC_YEAR,'DIGUVAGERIGADONA','9535105029','F','','P RAJASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Saranya A','',@CLASS_NAME,@ACADEMIC_YEAR,'BC COLONY','9515710336','F','','BALAJI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Shahitha V','',@CLASS_NAME,@ACADEMIC_YEAR,'INDIRA COLONY','9177901800','F','','VINOD KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VidyaSree K','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8008639631','F','','K.GUNA SEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Varisha.M.A','',@CLASS_NAME,@ACADEMIC_YEAR,'ANNURU','9791846313','F','','M.ABDUL LOTHEEF','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Aswin.M','',@CLASS_NAME,@ACADEMIC_YEAR,'(KNR) KOTACHERUVU','9600232563','M','','MUNIVELU.M','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Bhanuprakash N','',@CLASS_NAME,@ACADEMIC_YEAR,'PONAGALLU','9676376783','M','','M.MUNNENDRAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Charvik T','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','7569592625','M','','T.DHANASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Dheeraj.K','',@CLASS_NAME,@ACADEMIC_YEAR,'DHARMALACHERUVU','8096909300','M','','K.FAKAMBARAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Druva E','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9030070456','M','','E.SOMU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Harshavardhan P','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBA PURAM','8466803163','M','','P MUNNENDRA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kamran S','',@CLASS_NAME,@ACADEMIC_YEAR,'POLICE STATION (KNR)','8374840917','M','','D.AZARUDDUN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Kushal reddy K','',@CLASS_NAME,@ACADEMIC_YEAR,'CHINNAGARSTREET(KNR)','7993501899','M','','K.DINESH KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Lohith T','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9704323634','M','','T.RAGHUPATHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Nihal AASRITH .V','',@CLASS_NAME,@ACADEMIC_YEAR,'MANDAPAM(KNR)','8019317210','M','','V.Dillip Kumar','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Paarthiv sai K','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJASTREET(KNR)','8688896067','M','','K.RADHAKRISHNA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.Prithvik Sai','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','9704897949','M','','T.ELUMALAI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Sajith G','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9494369505','M','','G.GUNASEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Thaneesh K','',@CLASS_NAME,@ACADEMIC_YEAR,'SUROYYA PALLOM','9573864911','M','','MUNIRTHNAM REDDY','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Vedanth P','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9550569344','M','','LAKSHMIPATHI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Vikram adhithya M S','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9704915181','M','','M.S.SIVA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yashwanth N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','8106046480','M','','N.MAHESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('Yuvanandan EG','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9666199321','M','','E.GIRI BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
