/*

select * from SLN_ADMISIONS where CLASS ='1' and Section='B'
order by 1
*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='1',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham'

delete from SLN_ADMISIONS where CLASS ='1' and Section='B'


insert into SLN_ADMISIONS values('AADHYA SRI.C','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9985447056','F','','C Madhu','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('IDHAZHIKA .C','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVBPETA','8978744254','F','','C.DINESH KUMAR','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('T.DHAMINI','',@CLASS_NAME,@ACADEMIC_YEAR,'PACHIGUNTA','7382667948','F','','T SUBRAMANYAM','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('K.ISHITHA','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9985652664','F','','K MADHU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('LASYA SREE. M','',@CLASS_NAME,@ACADEMIC_YEAR,'KALIKIRINDULU','9553809472','F','','M PRAKASH','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MANASVI .B ','',@CLASS_NAME,@ACADEMIC_YEAR,'Kesavakupam','7093421470','F','','B Gopi','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('NAFEESA .','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8179785920','F','','S MUNNA','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PAVANI LAKSHMI .T ','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PURAM','9949021223','F','','T.DILLIBABU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHAESTHA .S','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9985626772','F','','S NAWAZ','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SRIYAS .C ','',@CLASS_NAME,@ACADEMIC_YEAR,'MITTAKANDRIGA','7730970680','F','','C KIRAN','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('THANVI SREE .C ','',@CLASS_NAME,@ACADEMIC_YEAR,'TKMPETA','9177766095','F','','K.ANILKUMAR','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VEEKSHITHA .M.M ','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','9177370054','F','','M.MUNEESWARAIAH','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('BHANUMURTHI .N ','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9676234209','F','','N.HARINADH','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HARSHA VARDHAN .K ','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDRIGA','9502529069','M','','K.VASU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HENVITH KUMAR .M','',@CLASS_NAME,@ACADEMIC_YEAR,'TKMPETA','8919999024','M','','M.BARATH KUMAR','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('JOSHITH .N ','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9490305208','M','','N.HARI','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MOKSHA NANDH ','',@CLASS_NAME,@ACADEMIC_YEAR,'Kathera palli','9676367678','M','','R Venkatesh','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('P.MOUNISH','',@CLASS_NAME,@ACADEMIC_YEAR,'MUNIREDDYKANDRIA','8374753500','M','','P.SRINIVASULU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('NISITH CHARAN ..D ','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9550303038','M','','T.DINAKAR','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PARDHA SARADHI .A ','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA','9550303457','M','','A.BALAJI','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SATHWIK REDDY.S ','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9000323728','M','','S VENKATAPATHI','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SWATHIK SAI .K ','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8688896067','M','','RADHAKRISHNA','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SHYAM .M ','',@CLASS_NAME,@ACADEMIC_YEAR,'KARVETINAGARAM','8179032184','M','','M.SRINIVASULU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('TEJESH .M ','',@CLASS_NAME,@ACADEMIC_YEAR,'Dharmala Cheruvu','9100691360','M','','Kanika Raju.M','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YASHVIN M','',@CLASS_NAME,@ACADEMIC_YEAR,'KOLAGUNTA','6309762635','M','','M MURALI','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YOGESH.P','',@CLASS_NAME,@ACADEMIC_YEAR,'BHARATHI PURAM','9100720248','M','','P.BALA KRISHNAREDDY','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MUKUNDAVARMA.P','',@CLASS_NAME,@ACADEMIC_YEAR,'OOTLU','8897740771','M','','P.PURUSHATHAM RAJU','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SUCHITHRA SREE.M','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','7708413346','F','','M.SANTHOSH','','B','',@LST_UPDATED_TMSP,@LST_UPATED_ID)
