
/*

select * from SLN_ADMISIONS where CLASS ='5' and Section='A'
order by 1

*/

declare @ACADEMIC_YEAR VARCHAR(10) ='2024-2025',
@CLASS_NAME varchar(10) ='5',
@LST_UPDATED_TMSP datetime = GETDATE(),
@LST_UPATED_ID varchar(50)='Purushotham',
@Section char(5) ='A'

delete from SLN_ADMISIONS where CLASS =@CLASS_NAME and Section=@Section


insert into SLN_ADMISIONS values('ARCHANA GRACE .V','',@CLASS_NAME,@ACADEMIC_YEAR,'ALLAGUNTA','6305566294','F','','V.SURESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('BAVANASHRIYAA.J','',@CLASS_NAME,@ACADEMIC_YEAR,'EAST STREET (KNR)','9440077774','F','','J. HARI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('BHOOMIKA .P','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','9008884617','F','','P BHASKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('GEETHA SREE.R','',@CLASS_NAME,@ACADEMIC_YEAR,'GAJULAKANDIGA','7483342776','F','','R.VENKATA RAMANA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HARINI.B','',@CLASS_NAME,@ACADEMIC_YEAR,'E.GERIGIDONA','9154423946','F','','B.YURVI KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('JASMITHA .K','',@CLASS_NAME,@ACADEMIC_YEAR,'BAJANAGUDI','7799486548','F','','K.NAGARAJU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MOKSHA SRI.K','',@CLASS_NAME,@ACADEMIC_YEAR,'RAGIMANU STREET','9182529141','F','','K.KUSHAL PRIYAVARDHAN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MOKSHITHA.P','',@CLASS_NAME,@ACADEMIC_YEAR,'NEARSAIBABATEMPLE(KNR)','9502508876','F','','P RAVI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MOKSHITHA.G','',@CLASS_NAME,@ACADEMIC_YEAR,'VIJAYAMAMBAPURAM','9515189120','F','','G HARI KRISHNA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PRATHIBA .A','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULA KANDRIGA(HW)','9989368526','F','','A KISHORE','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PRAVALIKA.G','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','9676332604','F','','G. RAJA SEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PRONVITHA. N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAGIMANU STREET','7330923092','F','','N CHANDRA SEKHAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('RABIYA .K.S','',@CLASS_NAME,@ACADEMIC_YEAR,'JANDA STREET (KNR)','9885924358','M','','K.S JILANI BASHA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('RAMONA E.T','',@CLASS_NAME,@ACADEMIC_YEAR,'TKM PETA','7337212878','M','','E.T THOJESWAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('ROSHINI .D','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR POLICE STATION','9959455978','M','','D.NOORUDDIN','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SADHANA .D','',@CLASS_NAME,@ACADEMIC_YEAR,'PADMA SARASSU','7670947800','M','','D.PRASADH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SANJANA .E.S','',@CLASS_NAME,@ACADEMIC_YEAR,'GERIGIDONA','9000580181','M','','E.S.YOGA MUNI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VARSHINI.N','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR POLICE STATION','9885341053','M','','N.HITHENDRA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VEDHASRI.P','',@CLASS_NAME,@ACADEMIC_YEAR,'KANKAMMAKANDRIGA','9701803526','M','','P.PRABHAKAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('YOHITHA SREE .R','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULAKANDRIGA(HW)','9550522658','M','','R RAJESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('BADHRI .D','',@CLASS_NAME,@ACADEMIC_YEAR,'BALASALAGUNTA','7382881996','M','','D.GOVIDHAGIRI VASULU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('CHAKRESH.D','',@CLASS_NAME,@ACADEMIC_YEAR,'BANDREVU COLONY','8688197411','M','','D.KOTI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('CHANIKYA .T','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','9676130620','M','','T.RAMESH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('CHETHAN .C','',@CLASS_NAME,@ACADEMIC_YEAR,'MITTA KANDRIGA(HW)','7730970680','M','','C.KIRAN KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('DAKSHITH REDDY.P','',@CLASS_NAME,@ACADEMIC_YEAR,'DAMARA KUPPAM','8179771427','M','','P.DHANAMJAYULU ','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('GAVESHKAR.P','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR POLIC STATION','9908685970','M','','P.NAVEEN KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('GOWTHAM .N','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR ITI (KNR)','8464089408','M','','N VARAPRASAD','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HASHMATHULLA K.S','',@CLASS_NAME,@ACADEMIC_YEAR,'JANDASTREET(KNR)','9885924358','M','','K.S.JILANI BASHA','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('HEMANTH KUMAR.S','',@CLASS_NAME,@ACADEMIC_YEAR,'NEAR DHARMARAJULI TEMPLE','9666613689','M','','S.ANAND','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('JAGADEESH .N','',@CLASS_NAME,@ACADEMIC_YEAR,'PONNAGALLU','9676376783','M','','N.MUNENDRAIAH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('JEEVAN .K','',@CLASS_NAME,@ACADEMIC_YEAR,'PHW(KNR)','8519926231','M','','K.RAMBABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('KARTHIK.N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULA KANDRIGA(HW)','9505003580','M','','N.GIRI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('KUSHAL .C','',@CLASS_NAME,@ACADEMIC_YEAR,'EDIGAPALLI','9701140801','M','','C.SIVA KUMAR','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('MOUNISH .P','',@CLASS_NAME,@ACADEMIC_YEAR,'M.KRISHNA PURAM','6364368120','M','','P.SWAMINATH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PARIKSHITH .C','',@CLASS_NAME,@ACADEMIC_YEAR,'KNR','8317639697','M','','C.GANESH BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PREM KUMAR .S','',@CLASS_NAME,@ACADEMIC_YEAR,'RKVB PETA','9502423318','M','','S.MUNI RATNAM','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('PURANJITH.R','',@CLASS_NAME,@ACADEMIC_YEAR,'PONNAGALLU','9642096431','M','','R.DORA BABU','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('SAHITH.N','',@CLASS_NAME,@ACADEMIC_YEAR,'RAJULA KANDRIGA(HW)','7675989564','M','','N. HARI','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VIKRAM .Bhati','',@CLASS_NAME,@ACADEMIC_YEAR,'BOZAAR STREET','8688534892','M','','Bhati SURESH ','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
insert into SLN_ADMISIONS values('VIVEK.A','',@CLASS_NAME,@ACADEMIC_YEAR,'RAGIMANU STREET','8985324770','M','','A.MADHAVAIH','',@Section,'',@LST_UPDATED_TMSP,@LST_UPATED_ID)
