SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP PROCEDURE IF EXISTS GetCollectionYearlySummary
GO
CREATE PROCEDURE GetCollectionYearlySummary
AS
BEGIN
    -- Main query with UNION ALL for total row
 with CTE AS (   SELECT 
        COLLECTION_TYPE,
        SUM(COLLECTION_AMOUNT) AS COLLECTION_AMOUNT
    FROM SLN_COLLECTION
    WHERE IS_DELETED = 0
    GROUP BY COLLECTION_TYPE

    UNION ALL

    SELECT 
        'Total' AS COLLECTION_TYPE,
        SUM(COLLECTION_AMOUNT) AS COLLECTION_AMOUNT
    FROM SLN_COLLECTION
    WHERE IS_DELETED = 0)

	select * from CTE order by COLLECTION_AMOUNT

    
END;
GO
