
IF OBJECT_ID('SLNSP_GETSAVEDFEEDETAILS', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE SLNSP_GETSAVEDFEEDETAILS;
END
GO

CREATE PROCEDURE SLNSP_GETSAVEDFEEDETAILS
   
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 			
		SELECT   FEE_ID
				,FEE_TYPE
				,STUDENT_NAME
				,FATHER_NAME
				,CLASS
				,SECTION
				,PAID_AMOUNT
				,BILL_NUMBER
				,[DESCRIPTION]
				,ACADEMIC_YEAR				
				,PAID_DATE	
				,VILLAGE_NAME
				,ADMISSION_ID
		FROM SLN_FEE
		Where IS_DELETED=0
		ORDER BY FEE_ID DESC
	
END;

GO


/*
exec SLNSP_GETSAVEDFEEDETAILS 'Char'
select * from SLN_ADMISIONS

SELECT FIRST_NAME
		FROM SLN_ADMISIONS
		where FIRST_NAME like '%char%'

*/