/****** Object:  StoredProcedure [dbo].[SLNSP_GETSTUDENTFEEDETAILSBYFILTERS]    Script Date: 28-Sep-24 11:59:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 DROP PROCEDURE IF EXISTS [SLNSP_GETSTUDENTFEEDETAILSBYFILTERS]
 GO

CREATE PROCEDURE [dbo].[SLNSP_GETSTUDENTFEEDETAILSBYFILTERS]	
	@STUDENT_NAME Varchar(50),
	@FATHER_NAME Varchar(50),
	@CLASS Varchar(10),
	@ACADEMIC_YEAR Varchar(10)
   
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance

		SELECT   FEE_ID  
				,FEE_TYPE  
				,STUDENT_NAME  
				,FATHER_NAME 
				,PAID_DATE 
				,PAID_AMOUNT  
				,BILL_NUMBER 
				,[DESCRIPTION]  
				,CLASS  
				,SECTION
				,ACADEMIC_YEAR 
				,VILLAGE_NAME  
				,ADMISSION_ID 
		FROM SLN_FEE
		where  STUDENT_NAME =@STUDENT_NAME AND FATHER_NAME=@FATHER_NAME
		AND CLASS=@CLASS and ACADEMIC_YEAR= @ACADEMIC_YEAR
		AND  IS_DELETED=0
		order by FEE_ID Desc
	
END;

GO