/****** Object:  StoredProcedure [dbo].[SLNSP_GETSTUDENTSBYCLASSANDYEAR]    Script Date: 28-Sep-24 11:59:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Drop Procedure if exists [SLNSP_GETSTUDENTSBYCLASSANDYEAR]

GO


CREATE PROCEDURE [dbo].[SLNSP_GETSTUDENTSBYCLASSANDYEAR]
    @CLASSNAME NVARCHAR(50),
	@ACADEMIC_YEAR Varchar(10)='',
	@SECTION Varchar(20)=''
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 if(@ACADEMIC_YEAR <> '' AND @CLASSNAME <> '')
	SELECT  FIRST_NAME ,
			LAST_NAME ,
			CLASS   ,
			ACADEMIC_YEAR ,
			VILLAGE_NAME ,	
			MOBILE_NUM   ,	
			GENDER ,
			AADHAR_NUM ,
			FATHER_NAME ,
			MOTHER_NAME ,	
			SECTION ,
			CASTE
	FROM 
		SLN_ADMISIONS
	WHERE 
		CLASS = @CLASSNAME AND ACADEMIC_YEAR = @ACADEMIC_YEAR AND SECTION =@SECTION
	ELSE
	BEGIN 
		SELECT  top 0 FIRST_NAME ,
			LAST_NAME ,
			CLASS   ,
			ACADEMIC_YEAR ,
			VILLAGE_NAME ,	
			MOBILE_NUM   ,	
			GENDER ,
			AADHAR_NUM ,
			FATHER_NAME ,
			MOTHER_NAME ,	
			SECTION ,
			CASTE
	FROM 
		SLN_ADMISIONS
	
	END
END;

GO

/*

	exec [SLNSP_GETSTUDENTSBYCLASSANDYEAR] 'Jr Inter','2024-2025','MPC'
	
	exec [SLNSP_GETSTUDENTSBYCLASSANDYEAR] 'Jr Inter','2024-2025','BiPC'
	
	exec [SLNSP_GETSTUDENTSBYCLASSANDYEAR] 'Jr Inter','2024-2025','CEC'
	exec [SLNSP_GETSTUDENTSBYCLASSANDYEAR] '1','2024-2025','A'
*/