
IF OBJECT_ID('SLNSP_GETSTUDENTSBYCLASSANDYEAR', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE SLNSP_GETSTUDENTSBYCLASSANDYEAR;
END
GO

CREATE PROCEDURE SLNSP_GETSTUDENTSBYCLASSANDYEAR
    @CLASSNAME NVARCHAR(50),
	@ACADEMIC_YEAR Varchar(10)=''
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 if(@ACADEMIC_YEAR <> '' AND @CLASSNAME <> '')
	SELECT  FIRST_NAME ,
			LAST_NAME ,
			CLASS   ,
			ACADEMIC_YEAR ,
			VILLAGE_NAME ,	
			MOBILE_NUM   ,	
			GENDER ,
			AADHAR_NUM ,
			FATHER_NAME ,
			MOTHER_NAME ,	
			SECTION ,
			CASTE
	FROM 
		SLN_ADMISIONS
	WHERE 
		CLASS = @CLASSNAME AND ACADEMIC_YEAR = @ACADEMIC_YEAR 
	ELSE
	BEGIN 
		SELECT  top 0 FIRST_NAME ,
			LAST_NAME ,
			CLASS   ,
			ACADEMIC_YEAR ,
			VILLAGE_NAME ,	
			MOBILE_NUM   ,	
			GENDER ,
			AADHAR_NUM ,
			FATHER_NAME ,
			MOTHER_NAME ,	
			SECTION ,
			CASTE
	FROM 
		SLN_ADMISIONS
	
	END
END;

GO


/*
exec SLNSP_GETSTUDENTSBYCLASSANDYEAR 'LKG','2023-2024'
exec SLNSP_GETSTUDENTSBYCLASSANDYEAR 'UKG','2024-2025'
exec SLNSP_GETSTUDENTSBYCLASSANDYEAR 'LKG',''

*/