
IF OBJECT_ID('SLNSP_EXPENSETYPEDETAILS', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE SLNSP_EXPENSETYPEDETAILS;
END
GO

CREATE PROCEDURE SLNSP_EXPENSETYPEDETAILS
   
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 
 SELECT EXPENSE_TYPE
		FROM (
			SELECT ' ' AS EXPENSE_TYPE, 0 AS SortOrder
			UNION ALL
			SELECT DISTINCT EXPENSE_TYPE, 1 AS SortOrder
			FROM SLN_EXPENSE_TYPE_LKP
		) AS EXPENSETYPEData
		ORDER BY SortOrder, EXPENSE_TYPE DESC

	
END;

GO


/*
exec SLNSP_EXPENSETYPEDETAILS 
select * from SLN_EXPENSE_TYPE_LKP

*/