

GO
/****** Object:  StoredProcedure [dbo].[SLNSP_GETCOLLECTIONREPORT]    Script Date: 27-Jul-24 10:13:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP PROCEDURE [dbo].[SLNSP_GETCOLLECTIONREPORT]

GO
CREATE PROCEDURE [dbo].[SLNSP_GETCOLLECTIONREPORT]			
			@COLLECTION_TYPE Varchar(50) ,	
			@FROM_DATE Date,
			@TO_DATE Date	
   
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 	
	IF(@COLLECTION_TYPE <>'ALL')
		BEGIN
			SELECT 
					COLLECTION_TYPE,				
					SUM(COLLECTION_AMOUNT) COLLECTION_AMOUNT				
			FROM SLN_COLLECTION
			where  COLLECTION_TYPE = @COLLECTION_TYPE
			AND ENTRY_DATE BETWEEN @FROM_DATE AND @TO_DATE
			AND IS_DELETED = 0
			GROUP BY
			COLLECTION_TYPE		
			order by COLLECTION_TYPE 
		END
	ELSE
		BEGIN
			SELECT 
					COLLECTION_TYPE,				
					SUM(COLLECTION_AMOUNT) COLLECTION_AMOUNT
			FROM SLN_COLLECTION
			where  
			ENTRY_DATE BETWEEN @FROM_DATE AND @TO_DATE
			AND IS_DELETED = 0
			GROUP BY
			COLLECTION_TYPE		
			order by COLLECTION_TYPE 
		END
	
END;

GO

/*

	exec [SLNSP_GETCOLLECTIONREPORT] 'ALL','2024-08-01','2024-09-01'
	exec [SLNSP_GETCOLLECTIONREPORT] 'Higher','2024-08-01','2024-09-01'
	
*/