IF OBJECT_ID('SLNSP_SLN_ADMISIONS_LOAD', 'P') IS NOT NULL
	BEGIN
		DROP PROCEDURE SLNSP_SLN_ADMISIONS_LOAD;
	END
	GO
	CREATE PROCEDURE [dbo].[SLNSP_SLN_ADMISIONS_LOAD]
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 
	INSERT INTO SLN_ADMISIONS
	SELECT  FIRST_NAME ,
			LAST_NAME ,
			CLASS   ,
			ACADEMIC_YEAR ,
			VILLAGE_NAME ,	
			MOBILE_NUM   ,	
			GENDER ,
			AADHAR_NUM ,
			FATHER_NAME ,
			MOTHER_NAME ,	
			SECTION ,
			CASTE,
			GETDATE(),
			LST_UPATED_ID,
			CAST(DISCOUNT_AMOUNT AS INT) ,
			CAST(IS_HALF_FEE AS BIT),
			CAST(IS_FREE_STUDENT AS BIT),
			CAST(IS_FEE_CLEAR AS BIT),
			DISCOUNT_DESCRIPTION
	FROM 
		SLN_ADMISIONS_STG
		
END;


/*
	select * from SLN_ADMISIONS
		select * from SLN_ADMISIONS_STG
*/