
IF OBJECT_ID('SLNSP_GETDISTINCTCLASSNAME', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE SLNSP_GETDISTINCTCLASSNAME;
END
GO

CREATE PROCEDURE SLNSP_GETDISTINCTCLASSNAME
   
AS
BEGIN
 SET NOCOUNT ON; -- Helps to reduce network traffic and improve performance
 
	SELECT 'Select Class' AS CLASS
	UNION ALL
	SELECT  distinct CLASS 
	FROM 
		SLN_ADMISIONS S
		--ORDER by S.CLASS
	
END;

GO


/*
exec SLNSP_GETDISTINCTCLASSNAME 

*/