
		/****** Object:  StoredProcedure [dbo].[SLNSP_GetBankTransactionDetails]    Script Date: 28-Sep-24 11:59:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 DROP PROCEDURE IF EXISTS SLNSP_GetBankTransactionDetails;
 GO

CREATE PROCEDURE [dbo].[SLNSP_GetBankTransactionDetails]
	@FETCHALL BIT =0
    
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN
	IF @FETCHALL =0
		Select TOP 15  TRANSACTION_ID,
						TRANSACTION_FROM,
						TRANSACTION_TO,
						TRANSACTION_AMOUNT,
						TRANSACTION_DATE,
						[DESCRIPTION],
						DEPOSITED_BY
		FROM SLN_BANK_TRANSACTIONS
		WHERE IS_DELETED=0
		ORDER BY TRANSACTION_ID DESC
	ELSE
		    Select  TRANSACTION_ID,
						TRANSACTION_FROM,
						TRANSACTION_TO,
						TRANSACTION_AMOUNT,
						TRANSACTION_DATE,
						[DESCRIPTION],
						DEPOSITED_BY
		FROM SLN_BANK_TRANSACTIONS
		WHERE IS_DELETED=0
		ORDER BY TRANSACTION_ID DESC
	 
	END   

END

/*
exec SLNSP_GetBankTransactionDetails 0
exec SLNSP_GetBankTransactionDetails 1
*/
GO