/****** Object:  StoredProcedure [dbo].[SLNSP_GETCOLLECTIONDETAILS]    Script Date: 28-Sep-24 11:59:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 DROP PROCEDURE IF EXISTS [SLNSP_GETCOLLECTIONDETAILS];
 GO

CREATE PROCEDURE [dbo].[SLNSP_GETCOLLECTIONDETAILS]
	@FETCHALL BIT =0
    
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN
	IF @FETCHALL =0
		Select TOP 15 COLLECTION_ID,
				COLLECTION_TYPE,
				COLLECTION_AMOUNT,
				BANK_DEPOSITED_AMOUNT,
				IN_CASH,
				[DESCRIPTION],				
				ENTRY_DATE
		FROM SLN_COLLECTION
		WHERE IS_DELETED=0
		ORDER BY COLLECTION_ID DESC
	ELSE
		Select COLLECTION_ID,
				COLLECTION_TYPE,
				COLLECTION_AMOUNT,
				BANK_DEPOSITED_AMOUNT,
				IN_CASH,
				[DESCRIPTION],
				ENTRY_DATE
		FROM SLN_COLLECTION
		WHERE IS_DELETED=0
		ORDER BY COLLECTION_ID DESC
	 
	END   

END

/*
exec SLNSP_GETCOLLECTIONDETAILS 0
exec SLNSP_GETCOLLECTIONDETAILS 1
*/
GO